### ISSUE TITLE
EpiModel Gallery Example: Empty Discordant Edgelist

### ISSUE THREAD

**Issue by andsv2** [EpiModel/EpiModel-Gallery#24]
EpiModel Gallery examples have been updated to take advantage of the changes to vital dynamics in EpiModel workflow. However, running through the examples, specifically "SEIR with All or Nothing Vaccine", has issues with empty discordant edgelists, that are not present when using base epimodel functions. The error occurs (using the SEIR example) here within the `infect` extension module:

```      # Set parameters on discordant edgelist data frame
      del$transProb <- inf.prob
      del$actRate <- act.rate
      del$finalProb <- 1 - (1 - del$transProb)^del$actRate
```

Because the discordant edgelist has no rows (and is not null) this causes an error. Adding this change to the conditional logic:

```    ## If any discordant pairs, proceed ##
    if (!(is.null(del)) && nrow(del) > 0) {
```
Solves this error. However I can not replicate this with base EpiModel and can not see why this is occurring. Any help or a second set of eyes on this would be appreciated. For reproduciability I'm using a seed of 123.

**Comment by AdrienLeGuillou** [comment]
@andsv2 so the problem is that `del <- discord_edgelist(dat, at)` should never have 0 rows and not be `NULL`?

If so, shouldn't we enforce that in the `discord_edgelist` function? By adding:

```r
del <- if (nrow(del) == 0) NULL else del

return(del)
```

This would ensure that a 0 row `del` cannot exist. Checking for `NULL` would the be sufficient

**Comment by andsv2** [comment]
@AdrienLeGuillou @smjenness so looking at `discord_edgelist`, it looks like `del` is set to `NULL` and then any operations done are based on whether the edgelist is empty or not. I think then at the end of the current `discord_edgelist` workflow, if the `del` data.frame has no rows after dropping inactive pairs then it should return `NULL`, otherwise return `del` as Adrien suggests instead of a check on number of rows as we discussed today. This keeps the original logic check in the Gallery examples and built in modules, and handles the check for the updated `discord_edgelist`.

**Comment by smjenness** [comment]
@andsv2 : I think this is resolved now, right?

**Comment by andsv2** [comment]
Yes. Closing now with change to logic in discordant edgelist/update plist.
