### ISSUE TITLE
Remove all references to nw object in Gallery examples

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel-Gallery#27]
For example:
https://github.com/EpiModel/EpiModel-Gallery/blob/master/2018-08-SIwithVitalDynamics/module-fx.R#L16-L20
https://github.com/EpiModel/EpiModel-Gallery/blob/master/2018-08-SIwithVitalDynamics/module-fx.R#L26

There may be others that I have not found. These dynamic updates to the nw object are both unnecessary (because they should be handled in `nwupdate.net`), and produce errors, when the model with run with `tergmLite = TRUE` (because there is no `dat$nw` object in this case.

**Comment by andsv2** [comment]
@smjenness 

All references to the network object have been removed from the gallery example functions, as well as redundant assignment of initial attributes in extension modules (all initial conditions are set at timestep 1 as expected). 

However, still getting errors locally and on Travis regarding documentation issues.
