### ISSUE TITLE
End-horizon simulation speed with parameter updater

### ISSUE THREAD

**Issue by gknowlt** [EpiModel/EpiModel-Gallery#35]
For the CEA gallery, pull request #33 incorporates the new parameter updater changes to EpiModel to handle the end horizon, while pull request #34 reflects the code before these changes. On my PC, executing the first netsim with the old code (1 core, 104 steps, 10 sims) takes 2.379 minutes. The updated version is sleeker in terms of the code, but the first netsim takes 1 minute longer at 3.376 min. In the clunky original set-up, the sim speeds up significantly during the end horizon but the same does not occur in the updated version of code. 
@AdrienLeGuillou 
@smjenness 
#33 
#34

**Comment by AdrienLeGuillou** [comment]
I can replicate this behavior on my machine.
I am investigating what does not work with the control updater module

**Comment by gknowlt** [comment]
@AdrienLeGuillou You are correct! I was using the CRAN version and not the Github version. That fixed the issue and everything is running quickly. Thank you for your help!
